apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: order-command-ms-pr-
spec:
  pipelineRef:
    name: order-command-ms-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: order-command-ms-git
    - name: image
      resourceRef:
        name: order-command-ms-image
  params:
    - name: "pathToContext"
      value: "./order-command-ms"
    - name: "pathToDockerFile"
      value: "Dockerfile.multistage"
    - name: "imageUrl"
      value: "docker-registry.default.svc:5000/eda-pipelines-sandbox/order-command-ms"
    - name: "imageTag"
      value: "latest"
    - name: "kanikoLoggingLevel"
      value: "info"
    - name: "kafkaServers"
      #value: "broker-3-j7fxtxtp5fs84205.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093, broker-2-j7fxtxtp5fs84205.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093, broker-1-j7fxtxtp5fs84205.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093, broker-5-j7fxtxtp5fs84205.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093, broker-0-j7fxtxtp5fs84205.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093, broker-4-j7fxtxtp5fs84205.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093"
      value: "broker-3-j7fxtxtp5fs84205.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-2-j7fxtxtp5fs84205.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093"
    - name: "targetEnvironment"
      value: "ICP"
    - name: "targetNamespace"
      value: "eda-pipelines-sandbox"
    - name: "releaseName"
      value: "order-command-ms"
  trigger:
    type: manual
  serviceAccount: tekton-eda-sa
