site_name: Container Shipment EDA reference implementation
repo_url: https://github.com/ibm-cloud-architecture/refarch-kc
google_analytics:
  - 'UA-149377589-3'
  - 'auto'
nav:
  - Introduction: index.md
  - Business problem statement:
    - Introduction: introduction.md
    - Event storming analysis: ./analysis/readme.md
  - From Analysis to Microservice Specifications: ./design/readme.md
  - Architecture: ./design/architecture.md
  - Development practices:
    - Order microservice with CQRS and Event Sourcing: https://ibm-cloud-architecture.github.io/refarch-kc-order-ms
    - Container microservice with Springboot - Spring Kafka and PostgreSQL:  https://ibm-cloud-architecture.github.io/refarch-kc-container-ms/springboot
    - Adopting Schema Registry and Avro: avro/avro.md
    - Saga applied to container solution: saga/saga.md
    - Dead letter pattern for this solution: dlq/dlq.md
    - Order rejection principle: ./rejection/rejection.md
    - Container anomaly: containerAnomaly/containerAnomaly.md
  - Related repositories: ./deployments/reposlist.md
  - Deployments:
    - Backing Services: ./deployments/backing-services.md
    - Application Components: ./deployments/application-components.md
  - Security: ./security.md
  - Integration tests:
    - Overview: ./itg-tests/itgtests.md
    - Happy Path: ./itg-tests/happy-path/happy_path.md
    - Saga Pattern: ./itg-tests/saga/saga.md
    - Order rejection: ./itg-tests/order-rejected/order_rejected.md
    - Dead letter: ./itg-tests/dlq/dlq.md
    - Container Anomaly: ./itg-tests/containerAnomaly/containerAnomaly.md
  - Demonstration script: ./demo/readme.md


theme:
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
