version: '3'
services:
    simulator:
        image: ibmcase/kcontainer-fleet-ms:latest
        hostname: fleetms
        ports:
            - "9080:9080"
            - "9443:9443"
        environment:
            KAFKA_ENV: ${KAFKA_ENV}
            KAFKA_BROKERS: ${KAFKA_BROKERS}
            KAFKA_APIKEY: ${KAFKA_APIKEY}
    web:
        image: ibmcase/kcontainer-ui:latest
        hostname: kcsolution
        ports:
            - "3010:3010"
        environment:
            KAFKA_ENV: ${KAFKA_ENV}
            KAFKA_BROKERS: ${KAFKA_BROKERS}
            KAFKA_APIKEY: ${KAFKA_APIKEY}
            FLEET_MS_URL: http://simulator:9080/fleetms
            ORDER_MS_URL: http://ordercmd:9080/orders
            ORDER_QUERY_MS_URL: http://orderquery:9080/orders
        depends_on:
            - simulator
            - ordercmd
            - orderquery
            - voyages
    ordercmd:
        image: ibmcase/kcontainer-order-command-ms:latest
        hostname: ordercmd
        ports:
            - "10080:9080"
        environment:
            KAFKA_ENV: ${KAFKA_ENV}
            KAFKA_BROKERS: ${KAFKA_BROKERS}
            KAFKA_APIKEY: ${KAFKA_APIKEY}
    orderquery:
        image: ibmcase/kcontainer-order-query-ms:latest
        hostname: orderquery
        ports:
            - "11080:9080"
        environment:
            KAFKA_ENV: ${KAFKA_ENV}
            KAFKA_BROKERS: ${KAFKA_BROKERS}
            KAFKA_APIKEY: ${KAFKA_APIKEY}
    voyages:
        image: ibmcase/kcontainer-voyages-ms:latest
        hostname: voyages
        ports:
            - "3100:3000"
        environment:
            KAFKA_ENV: ${KAFKA_ENV}
            KAFKA_BROKERS: ${KAFKA_BROKERS}
            KAFKA_APIKEY: ${KAFKA_APIKEY}
    springcontainerms:
        image: ibmcase/kcontainer-spring-container-ms:latest
        hostname: springcontainerms
        ports:
            - "12081:8080"
        environment:
            KAFKA_ENV: ${KAFKA_ENV}
            KAFKA_BROKERS: ${KAFKA_BROKERS}
            KAFKA_APIKEY: ${KAFKA_APIKEY}
            POSTGRESQL_URL: ${POSTGRESQL_URL}
            POSTGRESQL_USER: ${POSTGRESQL_USER}
            POSTGRESQL_PWD: ${POSTGRESQL_PWD}
            POSTGRESQL_CA_PEM: ${POSTGRESQL_CA_PEM}
