apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: order-command-ms-pipeline
spec:
  resources:
    - name: git-source
      type: git
    - name: image
      type: image
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
      type: string
    - name: pathToDockerFile
      description: The path to the projects Dockerfile (within the build context)
      type: string
      default: Dockerfile
    - name: imageUrl
      description: Url of image repository
      type: string
    - name: imageTag
      description: Tag to apply to the built image
      type: string
    - name: kanikoLoggingLevel
      type: string
      description: Logging level to apply to Kaniko build container
      default: info
    - name: chartName
      description: The name of the chart
      type: string
      default: ordercommandms
    - name: pathToChart
      description: The path to the chart within the workspace
      type: string
      default: order-command-ms/chart/ordercommandms
    - name: targetNamespace
      default: default
      type: string
    - name: targetEnvironment
      default: ICP
      type: string
    - name: releaseName
      type: string
      default: order-command-ms
    - name: kafkaServers
      type: string
      default: localhost:9092
  tasks:
  #- name: buildah
  #  taskRef:
  #    name: buildah
  #  params:
  #    - name: DOCKERFILE
  #      value: "$(params.pathToContext)/$(params.pathToDockerFile)"
  #  resources:
  #    inputs:
  #      - name: source
  #        resource: git-source
  #    outputs:
  #      - name: image
  #        resource: image
  - name: source-to-image
    taskRef:
      name: source-to-image
    #FOR TESTING PURPOSES ONLY - SKIP
    runAfter:
      - deploy-to-cluster
    params:
      - name: pathToContext
        value: "$(params.pathToContext)"
      - name: pathToDockerFile
        value: "$(params.pathToDockerFile)"
      - name: imageUrl
        value: "$(params.imageUrl)"
      - name: imageTag
        value: "$(params.imageTag)"
      - name: loggingLevel
        value: "$(params.kanikoLoggingLevel)"
    resources:
      inputs:
        - name: git-source
          resource: git-source
  - name: deploy-to-cluster
    taskRef:
      name: deploy-helm-template-via-kubectl
    #runAfter:
    #  - source-to-image
    params:
      - name: chartName
        value: "$(params.chartName)"
      - name: pathToChart
        value: "$(params.pathToChart)"
      - name: imageUrl
        value: "$(params.imageUrl)"
      - name: imageTag
        value: "$(params.imageTag)"
      - name: targetEnvironment
        value: "$(params.targetEnvironment)"
      - name: targetNamespace
        value: "$(params.targetNamespace)"
      - name: releaseName
        value: "$(params.releaseName)"
      - name: kafkaServers
        value: "$(params.kafkaServers)"
    resources:
      inputs:
        - name: git-source
          resource: git-source
