apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: order-command-ms-pipeline
spec:
  resources:
    - name: git-source
      type: git
    - name: image
      type: image
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
      type: string
    - name: pathToDockerFile
      description: The path to the projects Dockerfile (within the build context)
      type: string
      default: Dockerfile
    - name: imageUrl
      description: Url of image repository
      type: string
    - name: imageTag
      description: Tag to apply to the built image
      type: string
    - name: kanikoLoggingLevel
      type: string
      description: Logging level to apply to Kaniko build container
      default: info
  tasks:
  #- name: buildah
  #  taskRef:
  #    name: buildah
  #  params:
  #    - name: DOCKERFILE
  #      value: "$(params.pathToContext)/$(params.pathToDockerFile)"
  #  resources:
  #    inputs:
  #      - name: source
  #        resource: git-source
  #    outputs:
  #      - name: image
  #        resource: image
  - name: source-to-image
    taskRef:
      name: source-to-image
    params:
      - name: pathToContext
        value: "$(params.pathToContext)"
      - name: pathToDockerFile
        value: "$(params.pathToDockerFile)"
      - name: imageUrl
        value: "$(params.imageUrl)"
      - name: imageTag
        value: "$(params.imageTag)"
      - name: loggingLevel
        value: "$(params.kanikoLoggingLevel)"
    resources:
      inputs:
        - name: git-source
          resource: git-source
